services:
    app:
        container_name: jkt48-apis
        image: jkt48/apis:v0.1
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '6969:6969'
        restart: unless-stopped
        volumes:
            - jkt48-static:/jkt48/apis/static
            - jkt48-logs:/jkt48/apis/logs
volumes:
    jkt48-logs:
    jkt48-static:
